##### Code by J. Nam
##### Last updated: 2025-07-17
##### Code definition: Configuration parameters for PD_ElecStim_Transcriptome analysis

project_name: "PD_ElecStim_Transcriptome"

fastqc:
  dir_in: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/fastq/"
  dir_out: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/1.FastQC/"
  dir_log: "/data1/analysis/PD_elecStim_RNAseq_INU/Logfiles"
  file_format: "fastq.gz"
  job_name: "FastQC"
  job_limit: 20
  partition: "gar"
  thread: 4

trimgalore:
  dir_in: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/fastq/"
  dir_out: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/2.TrimGalore/"
  dir_log: "/data1/analysis/PD_elecStim_RNAseq_INU/Logfiles/"
  file_format: "fastq.gz"
  paired_end: "P"          # 'P' for paired-end, 'S' or other for single-end
  quality: 20
  thread: 4
  job_limit: 20
  partition: "gar"
  job_name: "TrimGal"

star_index:
  dir_log: "/data1/analysis/PD_elecStim_RNAseq_INU/Logfiles"
  fasta_path: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/reference/Rattus_norvegicus.mRatBN7.2.dna.toplevel.fa"
  gtf_path: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/reference/Rattus_norvegicus.mRatBN7.2.109.gtf"
  thread: 8
  job_limit: 2
  partition: "gar"
  job_name: "STARind"

star_align:
  dir_in: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/2.TrimGalore/"
  dir_out: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/3.STAR/"
  dir_log: "/data1/analysis/PD_elecStim_RNAseq_INU/Logfiles/"
  file_format: "fq.gz"
  paired_end: "P"        # 'P' for paired-end, 'S' or other for single-end
  thread: 8
  job_limit: 10
  partition: "gar"
  genome_index: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/reference/Rattus_norvegicus.mRatBN7.2.dna.toplevel.fa_index"
  job_name: "STARali"

featurecounts:
  dir_in: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/3.STAR/"
  dir_out: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/4.featureCounts/"
  dir_log: "/data1/analysis/PD_elecStim_RNAseq_INU/Logfiles/"
  paired_end: "P"          # 'P' for paired-end, 'S' or other for single-end
  thread: 8
  job_limit: 20
  partition: "gar"
  job_name: "featCnt"
  feature_type: "exon"
  strand: 2                # 0: unstranded, 1: forwardly stranded, 2: reversely stranded
  gtf_path: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/reference/Rattus_norvegicus.mRatBN7.2.109.gtf"

edger:
  dir_in: "/data1/analysis/PD_elecStim_RNAseq_INU/Preprocessing/4.featureCounts/"
  dir_out: "/data1/analysis/PD_elecStim_RNAseq_INU/DE_analysis/"
  gtf_type: "NCBI"
  gtf_path: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/reference/Rattus_norvegicus.mRatBN7.2.109.gtf"
  geneinfo_path: "/data1/analysis/PD_elecStim_RNAseq_INU/Rawdata/reference/"
  sampleinfo_path: "/data1/analysis/PD_elecStim_RNAseq_INU/DE_analysis/sampleinfo/SP.PD.sampleinfo.csv"
